<?php

namespace backend\modules\app\models;

use common\base\api\ActiveRecord;

/**
 * @property integer $id
 * @property integer $user_id
 * @property string $imei
 * @property string $token
 * @property string $type
 * @property integer $is_active
 */
class AppDeviceAPI extends ActiveRecord
{

    const TYPE_ANDROID = 'android';
    const TYPE_IOS = 'ios';

    public static function tableName()
    {
        return 'app_device';
    }

    public function fields()
    {
        $fields = parent::fields();
        return $fields;
    }

    public function apiFields()
    {
        //$fields = parent::apiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'user_id',
            'imei',
            'token',
            'type',
        ];
        return $fields;
    }

}