<?php

namespace backend\modules\app\models;

use common\base\api\ActiveRecord;

/**
 * @property string $id
 * @property integer $user_id
 * @property string $meta_key
 * @property string $meta_value
 * @property integer $last_update
 */
class AppMetaAPI extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'app_meta';
    }

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        return $fields;
    }

    public function apiFields()
    {
        //$fields = parent::apiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'user_id',
            'meta_key',
            'meta_value',
            'last_update'
        ];
        return $fields;
    }

}