<?php

namespace backend\modules\app\models;

use common\base\api\ActiveRecord;

/**
 * @property integer $id
 * @property integer $user_id
 * @property string $token
 * @property string $time
 * @property integer $is_expired
 *
 * @property AppUserAPI $user
 *
 */
class AppTokenAPI extends ActiveRecord
{
    public static function tableName()
    {
        return 'app_token';
    }

    public function fields()
    {
        $fields = parent::fields();
        return $fields;
    }

    public function apiFields()
    {
        //$fields = parent::apiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'user_id',
            'token',
            'time',
            'is_expired',
        ];
        return $fields;
    }


    public function getUser()
    {
        return $this->hasOne(AppUserAPI::className(), ['id' => 'user_id']);
    }
}