<?php

namespace backend\modules\system\models;

use common\base\api\ActiveRecord;

/**
 * @property integer $id
 * @property string $setting_key
 * @property string $setting_value
 * @property string $type
 */
class SystemSettingAPI extends ActiveRecord
{
    const TYPE_APPLICATION = 'application';
    const TYPE_LAYOUT = 'layout';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'system_setting';
    }

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        return $fields;
    }

    public function apiFields()
    {
        //$fields = parent::apiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'setting_key',
            'setting_value',
            'type'
        ];
        return $fields;
    }

}