<?php

namespace backend\modules\system\models;

use common\base\api\ActiveRecord;

/**
 * @property integer $id
 * @property string $language_code
 * @property string $language_name
 * @property integer $is_active
 */
class SystemLanguageAPI extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'system_language';
    }

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        return $fields;
    }

    public function apiFields()
    {
        //$fields = parent::apiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'language_code',
            'language_name',
            'is_active'
        ];
        return $fields;
    }

}