<?php

namespace backend\modules\system\models;

use common\base\api\ActiveRecord;

/**
 * @property integer $id
 * @property integer $role_id
 * @property string $module
 * @property string $obj
 * @property string $permission
 * @property integer $is_active
 */
class SystemRightAPI extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'system_right';
    }

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        return $fields;
    }

    public function apiFields()
    {
        //$fields = parent::apiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'role_id',
            'module',
            'obj',
            'permission',
            'is_active'
        ];
        return $fields;
    }

}