<?php

namespace backend\models;

use common\base\api\ActiveRecord;

/**
 * @property integer $id
 * @property string $loai_vb
 * @property integer $del_flg
 */
class MLoaiVbAPI extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'm_loai_vb';
    }

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        return $fields;
    }

    public function apiFields()
    {
        //$fields = parent::apiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'loai_vb',
            'del_flg'
        ];
        return $fields;
    }

}