<?php

namespace backend\models;

use common\base\api\ActiveRecord;

/**
 * @property integer $id
 * @property integer $id_donvi_gui
 * @property string $so_hieu
 * @property integer $id_loai_vanban
 * @property string $noidung_vanban
 * @property string $thoigian_banhanh
 * @property string $thoigian_nhan
 * @property integer $id_lanh_dao
 * @property integer $id_can_bo
 * @property string $thoigian_hoanthanh
 * @property integer $id_trang_thai
 * @property string $created_at
 * @property string $updated_at
 * @property integer $del_flg
 */
class VbDenAPI extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vb_den';
    }

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        return $fields;
    }

    public function apiFields()
    {
        //$fields = parent::apiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'id_donvi_gui',
            'so_hieu',
            'id_loai_vanban',
            'noidung_vanban',
            'thoigian_banhanh',
            'thoigian_nhan',
            'id_lanh_dao',
            'id_can_bo',
            'thoigian_hoanthanh',
            'id_trang_thai',
            'created_at',
            'updated_at',
            'del_flg'
        ];
        return $fields;
    }

}