<?php

namespace backend\models;

use Yii;

/**
 * @property integer $id
 * @property integer $id_nhom_vanban
 * @property string $so_hieu
 * @property integer $id_loai_vanban
 * @property string $noidung_vanban
 * @property string $thoigian_banhanh
 * @property string $noi_nhan
 * @property integer $id_nguoiki
 * @property string $file_dinhkem
 * @property string $created_at
 * @property string $updated_at
 * @property integer $del_flg
 *
 * @property string $uploadFolder
 * @property string $tableName
 */
class VbDiBase extends \yii\db\ActiveRecord
{

    public $tableName = 'vb_di';
    public $uploadFolder = 'vb-di';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vb_di';
    }

    public function afterDelete()
    {
        //$id = $this->id;
        $applicationUploadFolder = Yii::getAlias('@' . UPLOAD_DIR);
        $file_dinhkem_old = $this->file_dinhkem;
        if (strlen($file_dinhkem_old) > 0) {
            if (is_file($applicationUploadFolder . '/' . $this->uploadFolder . '/' . $file_dinhkem_old)) {
                unlink($applicationUploadFolder . '/' . $this->uploadFolder . '/' . $file_dinhkem_old);
            }
        }
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}