<?php

namespace backend\models;

use common\base\api\ActiveRecord;

/**
 * @property integer $id
 * @property string $so_hieu
 * @property string $noidung_vanban
 * @property string $thoigian_trinh
 * @property integer $id_nguoi_nhan
 * @property string $ghichu
 * @property string $created_at
 * @property string $updated_at
 * @property integer $del_flg
 */
class VbTrinhAPI extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vb_trinh';
    }

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        return $fields;
    }

    public function apiFields()
    {
        //$fields = parent::apiFields(); // TODO: Change the autogenerated stub
        $fields = [
            'id',
            'so_hieu',
            'noidung_vanban',
            'thoigian_trinh',
            'id_nguoi_nhan',
            'ghichu',
            'created_at',
            'updated_at',
            'del_flg'
        ];
        return $fields;
    }

}